/**
 * @type {number[]}
 */
export const COST_MODEL_PARAMS_V2 = [
    205665, // addInteger-cpu-arguments-intercept
    812, // addInteger-cpu-arguments-slope
    1, // addInteger-memory-arguments-intercept
    1, // addInteger-memory-arguments-slope
    1000, // appendByteString-cpu-arguments-intercept
    571, // appendByteString-cpu-arguments-slope
    0, // appendByteString-memory-arguments-intercept
    1, // appendByteString-memory-arguments-slope
    1000, // appendString-cpu-arguments-intercept
    24177, // appendString-cpu-arguments-slope
    4, // appendString-memory-arguments-intercept
    1, // appendString-memory-arguments-slope
    1000, // bData-cpu-arguments
    32, // bData-memory-arguments
    117366, // blake2b_256-cpu-arguments-intercept
    10475, // blake2b_256-cpu-arguments-slope
    4, // blake2b_256-memory-arguments
    23000, // cekApplyCost-exBudgetCPU
    100, // cekApplyCost-exBudgetMemory
    23000, // cekBuiltinCost-exBudgetCPU
    100, // cekBuiltinCost-exBudgetMemory
    23000, // cekConstCost-exBudgetCPU
    100, // cekConstCost-exBudgetMemory
    23000, // cekDelayCost-exBudgetCPU
    100, // cekDelayCost-exBudgetMemory
    23000, // cekForceCost-exBudgetCPU
    100, // cekForceCost-exBudgetMemory
    23000, // cekLamCost-exBudgetCPU
    100, // cekLamCost-exBudgetMemory
    100, // cekStartupCost-exBudgetCPU
    100, // cekStartupCost-exBudgetMemory
    23000, // cekVarCost-exBudgetCPU
    100, // cekVarCost-exBudgetMemory
    19537, // chooseData-cpu-arguments
    32, // chooseData-memory-arguments
    175354, // chooseList-cpu-arguments
    32, // chooseList-memory-arguments
    46417, // chooseUnit-cpu-arguments
    4, // chooseUnit-memory-arguments
    221973, // consByteString-cpu-arguments-intercept
    511, // consByteString-cpu-arguments-slope
    0, // consByteString-memory-arguments-intercept
    1, // consByteString-memory-arguments-slope
    89141, // constrData-cpu-arguments
    32, // constrData-memory-arguments
    497525, // decodeUtf8-cpu-arguments-intercept
    14068, // decodeUtf8-cpu-arguments-slope
    4, // decodeUtf8-memory-arguments-intercept
    2, // decodeUtf8-memory-arguments-slope
    196500, // divideInteger-cpu-arguments-constant
    453240, // divideInteger-cpu-arguments-model-arguments-intercept
    220, // divideInteger-cpu-arguments-model-arguments-slope
    0, // divideInteger-memory-arguments-intercept
    1, // divideInteger-memory-arguments-minimum
    1, // divideInteger-memory-arguments-slope
    1000, // encodeUtf8-cpu-arguments-intercept
    28662, // encodeUtf8-cpu-arguments-slope
    4, // encodeUtf8-memory-arguments-intercept
    2, // encodeUtf8-memory-arguments-slope
    245000, // equalsByteString-cpu-arguments-constant
    216773, // equalsByteString-cpu-arguments-intercept
    62, // equalsByteString-cpu-arguments-slope
    1, // equalsByteString-memory-arguments
    1060367, // equalsData-cpu-arguments-intercept
    12586, // equalsData-cpu-arguments-slope
    1, // equalsData-memory-arguments
    208512, // equalsInteger-cpu-arguments-intercept
    421, // equalsInteger-cpu-arguments-slope
    1, // equalsInteger-memory-arguments
    187000, // equalsString-cpu-arguments-constant
    1000, // equalsString-cpu-arguments-intercept
    52998, // equalsString-cpu-arguments-slope
    1, // equalsString-memory-arguments
    80436, // fstPair-cpu-arguments
    32, // fstPair-memory-arguments
    43249, // headList-cpu-arguments
    32, // headList-memory-arguments
    1000, // iData-cpu-arguments
    32, // iData-memory-arguments
    80556, // ifThenElse-cpu-arguments
    1, // ifThenElse-memory-arguments
    57667, // indexByteString-cpu-arguments
    4, // indexByteString-memory-arguments
    1000, // lengthOfByteString-cpu-arguments
    10, // lengthOfByteString-memory-arguments
    197145, // lessThanByteString-cpu-arguments-intercept
    156, // lessThanByteString-cpu-arguments-slope
    1, // lessThanByteString-memory-arguments
    197145, // lessThanEqualsByteString-cpu-arguments-intercept
    156, // lessThanEqualsByteString-cpu-arguments-slope
    1, // lessThanEqualsByteString-memory-arguments
    204924, // lessThanEqualsInteger-cpu-arguments-intercept
    473, // lessThanEqualsInteger-cpu-arguments-slope
    1, // lessThanEqualsInteger-memory-arguments
    208896, // lessThanInteger-cpu-arguments-intercept
    511, // lessThanInteger-cpu-arguments-slope
    1, // lessThanInteger-memory-arguments
    52467, // listData-cpu-arguments
    32, // listData-memory-arguments
    64832, // mapData-cpu-arguments
    32, // mapData-memory-arguments
    65493, // mkCons-cpu-arguments
    32, // mkCons-memory-arguments
    22558, // mkNilData-cpu-arguments
    32, // mkNilData-memory-arguments
    16563, // mkNilPairData-cpu-arguments
    32, // mkNilPairData-memory-arguments
    76511, // mkPairData-cpu-arguments
    32, // mkPairData-memory-arguments
    196500, // modInteger-cpu-arguments-constant
    453240, // modInteger-cpu-arguments-model-arguments-intercept
    220, // modInteger-cpu-arguments-model-arguments-slope
    0, // modInteger-memory-arguments-intercept
    1, // modInteger-memory-arguments-minimum
    1, // modInteger-memory-arguments-slope
    69522, // multiplyInteger-cpu-arguments-intercept
    11687, // multiplyInteger-cpu-arguments-slope
    0, // multiplyInteger-memory-arguments-intercept
    1, // multiplyInteger-memory-arguments-slope
    60091, // nullList-cpu-arguments
    32, // nullList-memory-arguments
    196500, // quotientInteger-cpu-arguments-constant
    453240, // quotientInteger-cpu-arguments-model-arguments-intercept
    220, // quotientInteger-cpu-arguments-model-arguments-slope
    0, // quotientInteger-memory-arguments-intercept
    1, // quotientInteger-memory-arguments-minimum
    1, // quotientInteger-memory-arguments-slope
    196500, // remainderInteger-cpu-arguments-constant
    453240, // remainderInteger-cpu-arguments-model-arguments-intercept
    220, // remainderInteger-cpu-arguments-model-arguments-slope
    0, // remainderInteger-memory-arguments-intercept
    1, // remainderInteger-memory-arguments-minimum
    1, // remainderInteger-memory-arguments-slope
    1159724, // serialiseData-cpu-arguments-intercept
    392670, // serialiseData-cpu-arguments-slope
    0, // serialiseData-memory-arguments-intercept
    2, // serialiseData-memory-arguments-slope
    806990, // sha2_256-cpu-arguments-intercept
    30482, // sha2_256-cpu-arguments-slope
    4, // sha2_256-memory-arguments
    1927926, // sha3_256-cpu-arguments-intercept
    82523, // sha3_256-cpu-arguments-slope
    4, // sha3_256-memory-arguments
    265318, // sliceByteString-cpu-arguments-intercept
    0, // sliceByteString-cpu-arguments-slope
    4, // sliceByteString-memory-arguments-intercept
    0, // sliceByteString-memory-arguments-slope
    85931, // sndPair-cpu-arguments
    32, // sndPair-memory-arguments
    205665, // subtractInteger-cpu-arguments-intercept
    812, // subtractInteger-cpu-arguments-slope
    1, // subtractInteger-memory-arguments-intercept
    1, // subtractInteger-memory-arguments-slope
    41182, // tailList-cpu-arguments
    32, // tailList-memory-arguments
    212342, // trace-cpu-arguments
    32, // trace-memory-arguments
    31220, // unBData-cpu-arguments
    32, // unBData-memory-arguments
    32696, // unConstrData-cpu-arguments
    32, // unConstrData-memory-arguments
    43357, // unIData-cpu-arguments
    32, // unIData-memory-arguments
    32247, // unListData-cpu-arguments
    32, // unListData-memory-arguments
    38314, // unMapData-cpu-arguments
    32, // unMapData-memory-arguments
    35892428, // verifyEcdsaSecp256k1Signature-cpu-arguments
    10, // verifyEcdsaSecp256k1Signature-memory-arguments
    57996947, // verifyEd25519Signature-cpu-arguments-intercept
    18975, // verifyEd25519Signature-cpu-arguments-slope
    10, // verifyEd25519Signature-memory-arguments
    38887044, // verifySchnorrSecp256k1Signature-cpu-arguments-intercept
    32947, // verifySchnorrSecp256k1Signature-cpu-arguments-slope
    10 // verifySchnorrSecp256k1Signature-memory-arguments
]
